version: "3.5"

services:
  db:
    image: mariadb:10.3
    container_name: db
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: db-phpmyadmin
    restart: always
    volumes:
      - ./phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    environment:
      - TZ=Asia/Tokyo
      - PMA_HOST=db
      - PMA_ARBITRARY=1
    ports: 
      - 8080:80
    networks:
      - app-network

networks:
  app-network:
    name: app_network
